<?php
add_filter( 'osf_customize_colors', 'osf_typography_custom_color', 10, 7 );
function osf_typography_custom_color($cssCode, $color_primary, $color_primary_hover, $color_secondary, $color_secondary_hover, $color_body, $color_heading) {
    $cssCode .= <<<CSS

blockquote cite,
.breadcrumb,
.breadcrumb a,
input[type="text"]::placeholder,
input[type="email"]::placeholder,
input[type="url"]::placeholder,
input[type="password"]::placeholder,
input[type="search"]::placeholder,
input[type="number"]::placeholder,
input[type="tel"]::placeholder,
input[type="range"]::placeholder,
input[type="date"]::placeholder,
input[type="month"]::placeholder,
input[type="week"]::placeholder,
input[type="time"]::placeholder,
input[type="datetime"]::placeholder,
input[type="datetime-local"]::placeholder,
input[type="color"]::placeholder,
input[type="text"],
input[type="email"],
input[type="url"],
input[type="password"],
input[type="search"],
input[type="number"],
input[type="tel"],
input[type="range"],
input[type="date"],
input[type="month"],
input[type="week"],
input[type="time"],
input[type="datetime"],
input[type="datetime-local"],
input[type="color"],
textarea::placeholder,
textarea,
.mainmenu-container li a span,
.tags-links a,
.site-footer a,
.c-body,
.site-header-account .account-links-menu li a,
.site-header-account .account-dashboard li a,
.comment-form a,
.tagcloud a,
.cart-collaterals .cart_totals th,
#payment .payment_methods li.woocommerce-notice,
#payment .payment_methods li.woocommerce-notice--info,
#payment .payment_methods li.woocommerce-info,
table.woocommerce-checkout-review-order-table th,
.opal-style-1.search-form-wapper .search-submit span,
.opal-style-1.search-form-wapper .search-submit span:before,
.elementor-nav-menu--dropdown a,
.elementor-search-form--skin-minimal .elementor-search-form__icon,
.elementor-search-form--skin-full_screen .elementor-search-form input.elementor-search-form__input[type="search"],
.woocommerce-shipping-fields .select2-container--default .select2-selection--single .select2-selection__rendered,
.woocommerce-billing-fields .select2-container--default .select2-selection--single .select2-selection__rendered,
.opal-currency_switcher .list-currency button[type="submit"],
li.product .posted_in a,
.select-items div,
.single-product div.type-product .summary .price del,
.single-product div.type-product .product_meta .tagged_as a,
.single-product div.type-product .product_meta .posted_in a,
.single-product div.type-product .product_meta .sku,
.single-product div.type-product .pbr-social-share a:not(:hover) {
  color: {$color_body}; }




.button-outline,
.woo-variation-swatches .variable-items-wrapper .button-variable-item:not(.radio-variable-item),
.btn-link,
.elementor-element .elementor-button-link .elementor-button,
.button-link,
.elementor-wpcf7-button-link input[type="button"][type="submit"],
.elementor-wpcf7-button-link input[type="submit"],
.elementor-wpcf7-button-link button[type="submit"],
.mailchimp-button-link button,
.mailchimp-button-link button[type="submit"],
.mailchimp-button-link input[type="submit"],
.widget-area strong,
h1,
.site-title,
h2,
h3,
.page-header .page-title,
h4,
h5,
h6,
.h1,
.h2,
.h3,
.h4,
.h5,
.h6,
.tags-links .tags-title,
blockquote,
.breadcrumb li.current,
.breadcrumb li .current-item,
.breadcrumb > span.current,
.breadcrumb > span .current-item,
.form-group .form-row label,
label,
th,
a,
.main-navigation .top-menu > li > a,
.menu-toggle,
.vertical-navigation ul.menu > li > a,
.page-numbers.next:not(ul),
.page-numbers.prev:not(ul),
.header-search .search-button,
.entry-meta .author a:not(:hover),
.pbr-social-share a,
.entry-content blockquote cite a,
.entry-content dt,
.entry-content th,
.site-header-account > a i,
.site-header-account > a .text-account,
.site-header-account > a .submenu-indicator,
.comment-content strong,
.comment-author,
.comment-author a,
.comment-metadata a.comment-edit-link,
.comment-reply-link,
.comment-content table th,
.comment-content dt,
.widget_search button[type="submit"],
.widget_meta a,
.widget_pages a,
.widget_archive a,
.widget_categories a,
.widget_nav_menu a,
.c-heading,
fieldset legend,
.post-navigation .nav-link a,
.author-wrapper .author-name,
.search .site-content .page-title,
#secondary .widget_product_categories .current-cat > a,
#secondary .widget_product_categories .current-cat > .count,
.widget_recent_entries li.item-recent-post a,
table.shop_table_responsive tbody th,
.filter-close,
table.cart:not(.wishlist_table) th,
.cart-collaterals .cart_totals .order-total .woocommerce-Price-amount,
.cart-collaterals .cart_totals .amount,
.woocommerce-checkout .woocommerce-form-coupon-toggle .woocommerce-info,
#payment .payment_methods > .wc_payment_method > label,
table.woocommerce-checkout-review-order-table .order-total .woocommerce-Price-amount,
table.woocommerce-checkout-review-order-table .product-name,
.woocommerce-billing-fields label,
.woocommerce-billing-fields > h3,
.page-header .woocommerce-billing-fields > .page-title,
.woocommerce-additional-fields label,
.cart th,
.shop_table th,
.woocommerce-account .woocommerce-MyAccount-content strong,
.woocommerce-account .woocommerce-MyAccount-content .woocommerce-Price-amount,
.osf-sorting .gridlist-toggle a.active,
.osf-sorting .gridlist-toggle a:hover,
#reviews .commentlist li .woocommerce-review__author,
.woocommerce-Tabs-panel table.shop_attributes th,
#osf-accordion-container table.shop_attributes th,
.single-product div.type-product .quantity_label,
.single-product div.type-product form.cart .quantity,
.single-product div.type-product table.variations label,
.woocommerce-tabs ul.tabs li a,
.woocommerce-tabs#osf-accordion-container [data-accordion] [data-control],
.woocommerce-widget-layered-nav .osf-label-type,
.woo-variation-swatches-stylesheet-disabled .variable-items-wrapper .variable-item:not(.radio-variable-item).button-variable-item:not(.disabled) .variable-item-span,
.elementor-element .elementor-widget-wp-widget-recent-posts .title-post a,
.elementor-featured-box-wrapper .elementor-featured-box-icon i,
.elementor-featured-box-wrapper .elementor-featured-box-title,
.elementor-widget-opal-image-hotspots .elementor-accordion .elementor-tab-title,
.elementor-nav-menu--main .elementor-nav-menu a,
.elementor-price-table__currency,
.elementor-price-table__integer-part,
.elementor-price-table__feature-inner span.item-active,
.elementor-price-table__period,
.countdown-times b,
.elementor-progress-percentage,
.elementor-widget-progress .elementor-title,
.elementor-teams-wrapper .elementor-team-name,
.elementor-widget-opal-testimonials .elementor-testimonial-title,
.elementor-widget-opal-testimonials .elementor-testimonial-name,
.header-button i,
.header-button .title,
.header-button .count-text,
.header-button .amount,
.header-button .text-wishlist,
.wishlist_table .product-price,
.stock .label,
li.product h2 a,
li.product h3 a,
li.product .page-header .page-title a,
.page-header li.product .page-title a,
li.product .woocommerce-loop-product__title a,
.shop-action .yith-wcqv-button,
.shop-action .yith-wcwl-add-to-wishlist > div > a,
.shop-action .compare,
.single-product div.type-product .product_meta,
.single-product div.type-product .pbr-social-share .social-share-header,
.widget_price_filter .price_slider_amount {
  color: {$color_heading}; }



.button-custom:hover i,
.breadcrumb a:hover,
.breadcrumb a:hover span,
.list-check li:before,
.main-navigation .top-menu > li:hover > a,
.main-navigation .top-menu > li:active > a,
.main-navigation .top-menu > li:focus > a,
.mainmenu-container li.current-menu-item > a,
.mainmenu-container li.current-menu-parent > a,
.mainmenu-container .menu-item > a:hover,
.page-numbers:not(ul),
.page-numbers.next:not(ul):hover,
.page-numbers.prev:not(ul):hover,
.site-header .header-group .search-submit:hover,
.site-header .header-group .search-submit:focus,
.entry-header .entry-title a:hover,
.entry-meta a,
.entry-meta .entry-date,
.entry-meta .meta-inner i,
.pbr-social-share a:hover,
.post-navigation > div:hover .nav-title,
.post-navigation > div:hover a,
.post-navigation > div:hover b,
.site-header-account > a:hover i,
.site-header-account > a:hover .text-account,
.site-header-account > a:hover .submenu-indicator,
.comment-author a:hover,
.comment-metadata a:hover,
.title-with-icon:before,
.widget_recent_entries li a:hover,
.widget_recent_entries li a:active,
.widget_recent_entries .post-date,
.button-outline-primary,
.cat-links a,
.elementor-wpcf7-button-outline_primary input[type="button"],
.elementor-wpcf7-button-outline_primary input[type="submit"],
.elementor-wpcf7-button-outline_primary button[type="submit"],
.mailchimp-button-outline_primary button,
.mailchimp-button-outline_primary button[type="submit"],
.mailchimp-button-outline_primary input[type="submit"],
.elementor-element .elementor-button-outline_primary .elementor-button,
.c-primary,
.mainmenu-container ul ul .menu-item > a:hover,
.mainmenu-container ul ul .menu-item > a:active,
.mainmenu-container ul ul .menu-item > a:focus,
.navigation-button .menu-toggle:hover,
.navigation-button .menu-toggle:focus,
.entry-content blockquote cite a:hover,
.site-header-account .account-dropdown a.register-link,
.site-header-account .account-dropdown a.lostpass-link,
.comment-form a:hover,
#secondary .elementor-widget-container h5:first-of-type,
.elementor-featured-box-wrapper:hover .elementor-featured-box-icon i:before,
.elementor-nav-menu-popup .mfp-close,
.site-header-cart .widget_shopping_cart .product_list_widget li a:hover,
.site-header-cart .widget_shopping_cart .product_list_widget li a:focus,
.site-header-cart .shopping_cart_nav .product_list_widget li a:hover,
.site-header-cart .shopping_cart_nav .product_list_widget li a:focus,
.woocommerce-checkout .woocommerce-form-coupon-toggle .woocommerce-info a,
.woocommerce-checkout .woocommerce-form-coupon-toggle .woocommerce-info a:hover,
.woocommerce-privacy-policy-link,
.opal-currency_switcher .list-currency button[type="submit"]:hover,
.opal-currency_switcher .list-currency li.active button[type="submit"],
ul.products li .posfed_in a:hover,
ul.products li.product .posfed_in a:hover,
.select-items div:hover,
.single-product div.type-product .woocommerce-product-gallery .woocommerce-product-gallery__trigger:hover,
.woocommerce-tabs ul.tabs li a:hover,
.woocommerce-tabs ul.tabs li.active a,
.button-wrapper #chart-button,
.product_list_widget a:hover,
.product_list_widget a:active,
.product_list_widget a:focus,
.woocommerce-product-list-3 a:hover,
.woocommerce-product-list-3 a:active,
.woocommerce-product-list-3 a:focus,
#secondary .elementor-widget-wp-widget-recent-posts a,
.elementor-element .elementor-widget-wp-widget-recent-posts .title-post a:hover,
.elementor-brand-wrapper .elementor-brand-description,
.contactform-content .form-title,
.elementor-opal-countdown-wrapper .elementor-countdown-digits,
.elementor-widget-icon-box.elementor-view-framed:hover .elementor-icon,
.elementor-widget-icon-box.elementor-view-framed:not(:hover) .elementor-icon,
.elementor-widget-icon-box.elementor-view-default:hover .elementor-icon,
.elementor-widget-icon-box.elementor-view-default:not(:hover) .elementor-icon,
.elementor-widget-icon-box:hover .elementor-icon-box-title,
.elementor-widget.elementor-widget-icon-list .elementor-icon-list-item:not(:hover) i,
.elementor-widget.elementor-widget-icon-list .elementor-icon-list-item:not(:hover) .elementor-icon-list-text,
.elementor-widget.elementor-widget-icon-list .elementor-icon-list-item:hover i,
.elementor-widget.elementor-widget-icon-list .elementor-icon-list-item:hover .elementor-icon-list-text,
.elementor-widget-icon.elementor-view-default .elementor-icon,
.elementor-widget-icon.elementor-view-framed .elementor-icon,
.elementor-widget-opal-image-hotspots .elementor-accordion .elementor-tab-title.elementor-active,
.elementor-nav-menu--main.elementor-nav-menu--layout-horizontal .elementor-nav-menu a.elementor-sub-item.elementor-item-active,
.elementor-nav-menu--main .elementor-item.highlighted,
.elementor-nav-menu--main .elementor-item.elementor-item-active,
.elementor-nav-menu--main .elementor-item:hover,
.elementor-nav-menu--main .elementor-item:focus,
.elementor-nav-menu--main .current-menu-ancestor .elementor-item.has-submenu,
.elementor-nav-menu--main .current-menu-item > .elementor-item,
.elementor-nav-menu--popup .elementor-item.highlighted,
.elementor-nav-menu--popup .elementor-item.elementor-item-active,
.elementor-nav-menu--popup .elementor-item:hover,
.elementor-nav-menu--popup .elementor-item:focus,
.elementor-nav-menu--popup .elementor-nav-menu--dropdown a:hover,
.elementor-nav-menu--popup .elementor-nav-menu--dropdown a.highlighted,
.elementor-nav-menu--dropdown:not(.mega-menu) a:hover,
.elementor-nav-menu--dropdown:not(.mega-menu) a.highlighted,
.elementor-nav-menu--dropdown:not(.mega-menu) a.has-submenu,
.elementor-menu-toggle:hover i,
.elementor-menu-toggle:hover .menu-toggle-title,
.elementor-widget-opal-phone:not(:hover) i,
.elementor-widget-opal-phone:not(:hover) .elementor-phone-title,
.elementor-widget-opal-phone:not(:hover) .elementor-phone-subtitle,
.portfolio .portfolio-content .entry-title a:hover,
.portfolio .entry-category a:hover,
.elementor-portfolio-style-overlay .portfolio .portfolio-content .entry-title a:hover,
.elementor-portfolio-style-overlay .portfolio .portfolio-content .entry-category a:hover,
.elementor-portfolio__filter:hover,
.single-portfolio-navigation .nav-link:hover span,
.elementor-button-default .elementor-button,
.elementor-search-form--skin-full_screen .elementor-search-form__toggle:hover,
.elementor-widget-social-icons.elementor-social-custom .elementor-social-icon:hover i,
.elementor-teams-wrapper .elementor-team-name:hover,
.elementor-video-icon,
.header-button:hover i,
.header-button:hover .title,
.header-button:hover .count-text,
.header-button:hover .amount,
.header-button:hover .text-wishlist,
.filter-toggle:hover,
.stock.in-stock .stock-availability,
.woocommerce-MyAccount-navigation ul li.is-active a,
.shop-action .yith-wcwl-add-to-wishlist > div.yith-wcwl-wishlistexistsbrowse > a:not(:hover),
.shop-action .yith-wcwl-add-to-wishlist > div.yith-wcwl-wishlistaddedbrowse > a:not(:hover),
.single-product div.type-product .entry-summary .yith-wcwl-add-to-wishlist > div.yith-wcwl-wishlistexistsbrowse > a:not(:hover),
.single-product div.type-product .entry-summary .yith-wcwl-add-to-wishlist > div.yith-wcwl-wishlistaddedbrowse > a:not(:hover) {
  color: {$color_primary->toCss()}; }


.f-primary {
  fill: {$color_primary->toCss()}; }


.mp-level::-webkit-scrollbar-thumb,
.page-numbers:not(ul):not(.dots):not(.next):not(.prev):hover,
.page-numbers:not(ul):not(.dots):not(.next):not(.prev):focus,
.page-numbers.current:not(ul):not(.dots):not(.next):not(.prev),
.more-link i,
.more-link:after,
.page-links a:hover .page-number,
.page-links a:focus .page-number,
.page-links .current .page-number,
.page-links > .page-number,
.scrollup,
.tagcloud a:hover,
.tagcloud a:focus,
.button-primary,
input[type="reset"],
input.secondary[type="button"],
input.secondary[type="reset"],
input.secondary[type="submit"],
input[type="button"],
input[type="submit"],
button[type="submit"],
.secondary-button .search-submit,
.elementor-wpcf7-button-primary input[type="button"][type="submit"],
.elementor-wpcf7-button-primary input[type="submit"],
.elementor-wpcf7-button-primary button[type="submit"],
.mailchimp-button-primary button,
.mailchimp-button-primary button[type="submit"],
.mailchimp-button-primary input[type="submit"],
.wc-proceed-to-checkout a.checkout-button,
.wishlist_table .product-add-to-cart .add_to_cart,
.widget_shopping_cart .buttons .button:nth-child(odd),
.button-default:hover,
.button-dark:hover,
.elementor-element .elementor-button-dark .elementor-button:hover,
.elementor-wpcf7-button-dark input:hover[type="submit"],
.elementor-wpcf7-button-dark button:hover[type="submit"],
.mailchimp-button-dark button:hover,
.mailchimp-button-dark input:hover[type="submit"],
form.woocommerce-form-login .button:hover[type="submit"],
form.register .button:hover[type="submit"],
.button-dark:active,
.elementor-element .elementor-button-dark .elementor-button:active,
.elementor-wpcf7-button-dark input:active[type="submit"],
.elementor-wpcf7-button-dark button:active[type="submit"],
.mailchimp-button-dark button:active,
.mailchimp-button-dark input:active[type="submit"],
form.woocommerce-form-login .button:active[type="submit"],
form.register .button:active[type="submit"],
.button-dark:focus,
.elementor-element .elementor-button-dark .elementor-button:focus,
.elementor-wpcf7-button-dark input:focus[type="submit"],
.elementor-wpcf7-button-dark button:focus[type="submit"],
.mailchimp-button-dark button:focus,
.mailchimp-button-dark input:focus[type="submit"],
form.woocommerce-form-login .button:focus[type="submit"],
form.register .button:focus[type="submit"],
.button-outline-dark:hover,
.elementor-element .elementor-button-outline_dark .elementor-button:hover,
.button-outline-dark:active,
.elementor-element .elementor-button-outline_dark .elementor-button:active,
.button-outline-dark:focus,
.elementor-element .elementor-button-outline_dark .elementor-button:focus,
.button-light:hover,
.elementor-element .elementor-button-light .elementor-button:hover,
.elementor-wpcf7-button-light input:hover[type="submit"],
.elementor-wpcf7-button-light button:hover[type="submit"],
.mailchimp-button-light button:hover,
.mailchimp-button-light input:hover[type="submit"],
.wishlist_table .product-add-to-cart .remove_from_wishlist:hover,
.wishlist_table.mobile li .additional-info-wrapper a.remove_from_wishlist:hover,
.button-light:active,
.elementor-element .elementor-button-light .elementor-button:active,
.elementor-wpcf7-button-light input:active[type="submit"],
.elementor-wpcf7-button-light button:active[type="submit"],
.mailchimp-button-light button:active,
.mailchimp-button-light input:active[type="submit"],
.wishlist_table .product-add-to-cart .remove_from_wishlist:active,
.wishlist_table.mobile li .additional-info-wrapper a.remove_from_wishlist:active,
.button-light:focus,
.elementor-element .elementor-button-light .elementor-button:focus,
.elementor-wpcf7-button-light input:focus[type="submit"],
.elementor-wpcf7-button-light button:focus[type="submit"],
.mailchimp-button-light button:focus,
.mailchimp-button-light input:focus[type="submit"],
.wishlist_table .product-add-to-cart .remove_from_wishlist:focus,
.wishlist_table.mobile li .additional-info-wrapper a.remove_from_wishlist:focus,
.elementor-element .elementor-button-primary .elementor-button,
.button-outline:hover,
.woo-variation-swatches .variable-items-wrapper .button-variable-item:hover:not(.radio-variable-item),
.button-outline:active,
.woo-variation-swatches .variable-items-wrapper .button-variable-item:active:not(.radio-variable-item),
.button-outline.active,
.woo-variation-swatches .variable-items-wrapper .active.button-variable-item:not(.radio-variable-item),
.show > .button-outline.dropdown-toggle,
.woo-variation-swatches .variable-items-wrapper .show > .dropdown-toggle.button-variable-item:not(.radio-variable-item),
.button-outline-primary:hover,
.cat-links a:hover,
.elementor-wpcf7-button-outline_primary input:hover[type="button"],
.elementor-wpcf7-button-outline_primary input:hover[type="submit"],
.elementor-wpcf7-button-outline_primary button:hover[type="submit"],
.mailchimp-button-outline_primary button:hover,
.mailchimp-button-outline_primary input:hover[type="submit"],
.button-outline-primary:active,
.cat-links a:active,
.elementor-wpcf7-button-outline_primary input:active[type="button"],
.elementor-wpcf7-button-outline_primary input:active[type="submit"],
.elementor-wpcf7-button-outline_primary button:active[type="submit"],
.mailchimp-button-outline_primary button:active,
.mailchimp-button-outline_primary input:active[type="submit"],
.button-outline-primary.active,
.cat-links a.active,
.elementor-wpcf7-button-outline_primary input.active[type="button"],
.elementor-wpcf7-button-outline_primary input.active[type="submit"],
.elementor-wpcf7-button-outline_primary button.active[type="submit"],
.mailchimp-button-outline_primary button.active,
.mailchimp-button-outline_primary input.active[type="submit"],
.show > .button-outline-primary.dropdown-toggle,
.cat-links .show > a.dropdown-toggle,
.elementor-wpcf7-button-outline_primary .show > input.dropdown-toggle[type="button"],
.elementor-wpcf7-button-outline_primary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-outline_primary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-outline_primary .show > button.dropdown-toggle,
.mailchimp-button-outline_primary .show > input.dropdown-toggle[type="submit"],
.elementor-element .elementor-button-outline_primary .elementor-button:hover,
.elementor-element .elementor-button-outline_primary .elementor-button:active,
.elementor-element .elementor-button-outline_primary .elementor-button:focus,
.bg-primary,
.owl-theme .owl-nav [class*='owl-']:hover:before,
.elementor-element .elementor-button-secondary .elementor-button:after,
.elementor-element .elementor-button-outline_secondary .elementor-button:before,
.elementor-element .elementor-button-link .elementor-button .elementor-button-icon,
.elementor-cta .elementor-cta_circle,
.elementor-widget-divider .elementor-divider-separator:before,
.elementor-icon-bg-yes .elementor-featured-box-wrapper .elementor-featured-box-icon i:after,
.elementor-flip-box__front,
.elementor-widget-icon-box.elementor-view-stacked:not(:hover) .elementor-icon,
.elementor-widget-icon-box.elementor-view-stacked:hover .elementor-icon,
.elementor-text-underline-yes .elementor-icon-list-item:hover .elementor-icon-list-text:before,
.elementor-widget-icon.elementor-view-stacked .elementor-icon,
.elementor-widget-opal-image-hotspots .scrollbar-inner > .scroll-element .scroll-bar,
.opal-image-hotspots-main-icons .opal-image-hotspots-icon,
.elementor-widget-opal-image-gallery .gallery-item-overlay,
.elementor-widget-opal-image-gallery .elementor-galerry__filter.elementor-active,
.elementor-nav-menu--main.elementor-nav-menu--layout-horizontal:not(.e--pointer-framed) .elementor-nav-menu > li.current-menu-parent > a:before,
.elementor-nav-menu--main.elementor-nav-menu--layout-horizontal:not(.e--pointer-framed) .elementor-nav-menu > li.current-menu-parent > a:after,
.elementor-nav-menu--main.e--pointer-dot .elementor-item.elementor-item-active:before,
.elementor-nav-menu--main.e--pointer-dot .elementor-item:not(:hover):before,
.elementor-nav-menu--main.e--pointer-dot .elementor-item:hover:before,
.elementor-nav-menu--main:not(.e--pointer-framed) .elementor-item.elementor-item-active:before,
.elementor-nav-menu--main:not(.e--pointer-framed) .elementor-item.elementor-item-active:after,
.elementor-nav-menu--main:not(.e--pointer-framed) .elementor-item:before,
.elementor-nav-menu--main:not(.e--pointer-framed) .elementor-item:after,
.elementor-nav-menu--popup.e--pointer-dot .elementor-item.elementor-item-active:before,
.elementor-nav-menu--popup.e--pointer-dot .elementor-item:hover:before,
.e--pointer-dot .elementor-item:before,
.e--pointer-underline .elementor-item .menu-title:before,
.e--pointer-underline .elementor-item .menu-title:after,
.single-portfolio-summary .pbr-social-share a:hover,
.opal-product-tooltipster .tooltipster-content,
.elementor-teams-wrapper .team-icon-socials a,
.timeline-item .timeline-thumbnail:after,
.header-button:hover .count,
.notification-added-to-cart .ns-content,
#payment .place-order .button:hover,
.shop-action a[class*="product_type_"]:before,
.shop-action .yith-wcqv-button:hover,
.shop-action .yith-wcwl-add-to-wishlist > div > a:hover,
.shop-action .compare:hover,
.single-product[class*="opal-comment-form"] .comment-form .form-submit .submit:hover,
.single-product[class*="opal-comment-form"] .comment-form .form-submit .submit:active,
.single-product[class*="opal-comment-form"] .comment-form .form-submit .submit:focus,
.widget_price_filter .ui-slider .ui-slider-handle,
.widget_price_filter .ui-slider .ui-slider-range,
.handheld-footer-bar .cart .footer-cart-contents .count {
  background-color: {$color_primary->toCss()}; }



.button-outline-secondary,
.elementor-wpcf7-button-outline_secondary input[type="button"][type="submit"],
.elementor-wpcf7-button-outline_secondary input[type="submit"],
.elementor-wpcf7-button-outline_secondary button[type="submit"],
.mailchimp-button-outline_secondary button,
.mailchimp-button-outline_secondary button[type="submit"],
.mailchimp-button-outline_secondary input[type="submit"],
.elementor-element.elementor-button-link .elementor-button:hover,
blockquote:before,
input[type="text"]:focus,
input[type="email"]:focus,
input[type="url"]:focus,
input[type="password"]:focus,
input[type="search"]:focus,
input[type="number"]:focus,
input[type="tel"]:focus,
input[type="range"]:focus,
input[type="date"]:focus,
input[type="month"]:focus,
input[type="week"]:focus,
input[type="time"]:focus,
input[type="datetime"]:focus,
input[type="datetime-local"]:focus,
input[type="color"]:focus,
textarea:focus,
.tagcloud a:hover,
.tagcloud a:focus,
.button-primary,
input[type="reset"],
input.secondary[type="button"],
input.secondary[type="reset"],
input.secondary[type="submit"],
input[type="button"],
input[type="submit"],
button[type="submit"],
.secondary-button .search-submit,
.elementor-wpcf7-button-primary input[type="button"][type="submit"],
.elementor-wpcf7-button-primary input[type="submit"],
.elementor-wpcf7-button-primary button[type="submit"],
.mailchimp-button-primary button,
.mailchimp-button-primary button[type="submit"],
.mailchimp-button-primary input[type="submit"],
.wc-proceed-to-checkout a.checkout-button,
.wishlist_table .product-add-to-cart .add_to_cart,
.widget_shopping_cart .buttons .button:nth-child(odd),
.button-default:hover,
.button-dark:hover,
.elementor-element .elementor-button-dark .elementor-button:hover,
.elementor-wpcf7-button-dark input:hover[type="submit"],
.elementor-wpcf7-button-dark button:hover[type="submit"],
.mailchimp-button-dark button:hover,
.mailchimp-button-dark input:hover[type="submit"],
form.woocommerce-form-login .button:hover[type="submit"],
form.register .button:hover[type="submit"],
.button-dark:active,
.elementor-element .elementor-button-dark .elementor-button:active,
.elementor-wpcf7-button-dark input:active[type="submit"],
.elementor-wpcf7-button-dark button:active[type="submit"],
.mailchimp-button-dark button:active,
.mailchimp-button-dark input:active[type="submit"],
form.woocommerce-form-login .button:active[type="submit"],
form.register .button:active[type="submit"],
.button-dark:focus,
.elementor-element .elementor-button-dark .elementor-button:focus,
.elementor-wpcf7-button-dark input:focus[type="submit"],
.elementor-wpcf7-button-dark button:focus[type="submit"],
.mailchimp-button-dark button:focus,
.mailchimp-button-dark input:focus[type="submit"],
form.woocommerce-form-login .button:focus[type="submit"],
form.register .button:focus[type="submit"],
.button-outline-dark:hover,
.elementor-element .elementor-button-outline_dark .elementor-button:hover,
.button-outline-dark:active,
.elementor-element .elementor-button-outline_dark .elementor-button:active,
.button-outline-dark:focus,
.elementor-element .elementor-button-outline_dark .elementor-button:focus,
.button-light:hover,
.elementor-element .elementor-button-light .elementor-button:hover,
.elementor-wpcf7-button-light input:hover[type="submit"],
.elementor-wpcf7-button-light button:hover[type="submit"],
.mailchimp-button-light button:hover,
.mailchimp-button-light input:hover[type="submit"],
.wishlist_table .product-add-to-cart .remove_from_wishlist:hover,
.wishlist_table.mobile li .additional-info-wrapper a.remove_from_wishlist:hover,
.button-light:active,
.elementor-element .elementor-button-light .elementor-button:active,
.elementor-wpcf7-button-light input:active[type="submit"],
.elementor-wpcf7-button-light button:active[type="submit"],
.mailchimp-button-light button:active,
.mailchimp-button-light input:active[type="submit"],
.wishlist_table .product-add-to-cart .remove_from_wishlist:active,
.wishlist_table.mobile li .additional-info-wrapper a.remove_from_wishlist:active,
.button-light:focus,
.elementor-element .elementor-button-light .elementor-button:focus,
.elementor-wpcf7-button-light input:focus[type="submit"],
.elementor-wpcf7-button-light button:focus[type="submit"],
.mailchimp-button-light button:focus,
.mailchimp-button-light input:focus[type="submit"],
.wishlist_table .product-add-to-cart .remove_from_wishlist:focus,
.wishlist_table.mobile li .additional-info-wrapper a.remove_from_wishlist:focus,
.elementor-element .elementor-button-primary .elementor-button,
.button-outline-primary,
.cat-links a,
.elementor-wpcf7-button-outline_primary input[type="button"],
.elementor-wpcf7-button-outline_primary input[type="submit"],
.elementor-wpcf7-button-outline_primary button[type="submit"],
.mailchimp-button-outline_primary button,
.mailchimp-button-outline_primary button[type="submit"],
.mailchimp-button-outline_primary input[type="submit"],
.elementor-element .elementor-button-outline_primary .elementor-button,
.button-outline:hover,
.woo-variation-swatches .variable-items-wrapper .button-variable-item:hover:not(.radio-variable-item),
.button-outline:active,
.woo-variation-swatches .variable-items-wrapper .button-variable-item:active:not(.radio-variable-item),
.button-outline.active,
.woo-variation-swatches .variable-items-wrapper .active.button-variable-item:not(.radio-variable-item),
.show > .button-outline.dropdown-toggle,
.woo-variation-swatches .variable-items-wrapper .show > .dropdown-toggle.button-variable-item:not(.radio-variable-item),
.button-outline-primary:hover,
.cat-links a:hover,
.elementor-wpcf7-button-outline_primary input:hover[type="button"],
.elementor-wpcf7-button-outline_primary input:hover[type="submit"],
.elementor-wpcf7-button-outline_primary button:hover[type="submit"],
.mailchimp-button-outline_primary button:hover,
.mailchimp-button-outline_primary input:hover[type="submit"],
.button-outline-primary:active,
.cat-links a:active,
.elementor-wpcf7-button-outline_primary input:active[type="button"],
.elementor-wpcf7-button-outline_primary input:active[type="submit"],
.elementor-wpcf7-button-outline_primary button:active[type="submit"],
.mailchimp-button-outline_primary button:active,
.mailchimp-button-outline_primary input:active[type="submit"],
.button-outline-primary.active,
.cat-links a.active,
.elementor-wpcf7-button-outline_primary input.active[type="button"],
.elementor-wpcf7-button-outline_primary input.active[type="submit"],
.elementor-wpcf7-button-outline_primary button.active[type="submit"],
.mailchimp-button-outline_primary button.active,
.mailchimp-button-outline_primary input.active[type="submit"],
.show > .button-outline-primary.dropdown-toggle,
.cat-links .show > a.dropdown-toggle,
.elementor-wpcf7-button-outline_primary .show > input.dropdown-toggle[type="button"],
.elementor-wpcf7-button-outline_primary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-outline_primary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-outline_primary .show > button.dropdown-toggle,
.mailchimp-button-outline_primary .show > input.dropdown-toggle[type="submit"],
.elementor-element .elementor-button-outline_primary .elementor-button:hover,
.elementor-element .elementor-button-outline_primary .elementor-button:active,
.elementor-element .elementor-button-outline_primary .elementor-button:focus,
.b-primary,
.owl-theme .owl-nav [class*='owl-']:hover:before,
.elementor-widget-icon-box.elementor-view-framed:hover .elementor-icon,
.elementor-widget-icon-box.elementor-view-framed:not(:hover) .elementor-icon,
.elementor-widget-icon.elementor-view-default .elementor-icon,
.elementor-widget-icon.elementor-view-framed .elementor-icon,
.elementor-widget-opal-image-gallery .elementor-galerry__filter.elementor-active:before,
.mc4wp-form-fields:focus-within,
.e--pointer-framed .elementor-item.elementor-item-active:before,
.e--pointer-framed .elementor-item.elementor-item-active:after,
.e--pointer-framed .elementor-item:before,
.e--pointer-framed .elementor-item:after,
.elementor-nav-menu--main > .elementor-nav-menu,
.elementor-nav-menu--main .elementor-nav-menu ul,
ul.elementor-price-table__features-list,
.elementor-search-form__container:not(.elementor-search-form--full-screen):focus-within,
.elementor-search-form--skin-full_screen .elementor-search-form__toggle:hover,
.site-header-cart .widget_shopping_cart,
#payment .place-order .button:hover,
.shop-action .yith-wcqv-button:hover,
.shop-action .yith-wcwl-add-to-wishlist > div > a:hover,
.shop-action .compare:hover,
.single-product div.type-product .woocommerce-product-gallery .flex-control-thumbs li img.flex-active,
.single-product div.type-product .woocommerce-product-gallery .flex-control-thumbs li:hover img,
.single-product[class*="opal-comment-form"] .comment-form .form-submit .submit:hover,
.single-product[class*="opal-comment-form"] .comment-form .form-submit .submit:active,
.single-product[class*="opal-comment-form"] .comment-form .form-submit .submit:focus,
.woocommerce-tabs ul.tabs li a:hover:after,
.woocommerce-tabs ul.tabs li.active a:after,
.otf-product-recently-content li:hover .product-thumbnail img {
  border-color: {$color_primary->toCss()}; }


.site-header-account .account-dropdown .account-wrap,
.opal-product-tooltipster.tooltipster-base.tooltipster-top .tooltipster-arrow-background {
  border-top-color: {$color_primary->toCss()}; }


.main-navigation .top-menu > li:hover:before,
.main-navigation .top-menu > li:active:before,
.main-navigation .top-menu > li:focus:before,
.site-header-account .account-dropdown .account-wrap:before,
.elementor-nav-menu--layout-horizontal .elementor-nav-menu li.menu-item-has-children:before,
.elementor-nav-menu--layout-horizontal .elementor-nav-menu li.has-mega-menu:before,
.site-header-cart .widget_shopping_cart:before {
  border-bottom-color: {$color_primary->toCss()}; }


.opal-product-tooltipster.tooltipster-base.tooltipster-left .tooltipster-arrow-background {
  border-left-color: {$color_primary->toCss()}; }



.shop-action a[class*="product_type_"] {
    background-image: linear-gradient(to right, {$color_primary->toCss()} 0, {$color_primary->toCss()} 100%);
}



.btn-link:focus,
.elementor-element .elementor-button-link .elementor-button:focus,
.btn-link:hover,
.elementor-element .elementor-button-link .elementor-button:hover,
.button-link:focus,
.elementor-wpcf7-button-link input:focus[type="submit"],
.elementor-wpcf7-button-link button:focus[type="submit"],
.mailchimp-button-link button:focus,
.mailchimp-button-link input:focus[type="submit"],
.button-link:hover,
.elementor-wpcf7-button-link input:hover[type="submit"],
.elementor-wpcf7-button-link button:hover[type="submit"],
.mailchimp-button-link button:hover,
.mailchimp-button-link input:hover[type="submit"],
a:hover,
a:active,
.widget_search button[type="submit"]:hover,
.widget_search button[type="submit"]:focus,
.elementor-widget-opal-phone:hover i,
.elementor-widget-opal-phone:hover .elementor-phone-title,
.elementor-widget-opal-phone:hover .elementor-phone-subtitle,
.elementor-search-form .elementor-search-form__submit:active,
.elementor-search-form .elementor-search-form__submit:hover,
li.product .posted_in a:hover,
.single-product div.type-product .product_meta .tagged_as a:hover,
.single-product div.type-product .product_meta .posted_in a:hover {
  color: {$color_primary_hover->toCss()}; }


.tags-links a:hover,
.scrollup:hover,
.button-primary:hover,
input:hover[type="reset"],
input:hover[type="button"],
input:hover[type="submit"],
button:hover[type="submit"],
.secondary-button .search-submit:hover,
.elementor-wpcf7-button-primary input:hover[type="submit"],
.elementor-wpcf7-button-primary button:hover[type="submit"],
.mailchimp-button-primary button:hover,
.wc-proceed-to-checkout a.checkout-button:hover,
.wishlist_table .product-add-to-cart .add_to_cart:hover,
.widget_shopping_cart .buttons .button:hover:nth-child(odd),
.button-primary:active,
input:active[type="reset"],
input:active[type="button"],
input:active[type="submit"],
button:active[type="submit"],
.secondary-button .search-submit:active,
.elementor-wpcf7-button-primary input:active[type="submit"],
.elementor-wpcf7-button-primary button:active[type="submit"],
.mailchimp-button-primary button:active,
.wc-proceed-to-checkout a.checkout-button:active,
.wishlist_table .product-add-to-cart .add_to_cart:active,
.widget_shopping_cart .buttons .button:active:nth-child(odd),
.button-primary.active,
input.active[type="reset"],
input.active[type="button"],
input.active[type="submit"],
button.active[type="submit"],
.secondary-button .active.search-submit,
.elementor-wpcf7-button-primary input.active[type="submit"],
.elementor-wpcf7-button-primary button.active[type="submit"],
.mailchimp-button-primary button.active,
.wc-proceed-to-checkout a.active.checkout-button,
.wishlist_table .product-add-to-cart .active.add_to_cart,
.widget_shopping_cart .buttons .active.button:nth-child(odd),
.show > .button-primary.dropdown-toggle,
.show > input.dropdown-toggle[type="reset"],
.show > input.dropdown-toggle[type="button"],
.show > input.dropdown-toggle[type="submit"],
.show > button.dropdown-toggle[type="submit"],
.secondary-button .show > .dropdown-toggle.search-submit,
.elementor-wpcf7-button-primary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-primary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-primary .show > button.dropdown-toggle,
.mailchimp-button-primary .show > input.dropdown-toggle[type="submit"],
.wc-proceed-to-checkout .show > a.dropdown-toggle.checkout-button,
.wishlist_table .product-add-to-cart .show > .dropdown-toggle.add_to_cart,
.widget_shopping_cart .buttons .show > .dropdown-toggle.button:nth-child(odd),
.elementor-element .elementor-button-primary .elementor-button:hover,
.elementor-element .elementor-button-primary .elementor-button:active,
.elementor-element .elementor-button-primary .elementor-button:focus,
.single-product div.type-product .entry-summary .yith-wcwl-add-to-wishlist > div > a:hover,
.single-product div.type-product .entry-summary .compare:hover {
  background-color: {$color_primary_hover->toCss()}; }


.tags-links a:hover,
.button-primary:hover,
input:hover[type="reset"],
input:hover[type="button"],
input:hover[type="submit"],
button:hover[type="submit"],
.secondary-button .search-submit:hover,
.elementor-wpcf7-button-primary input:hover[type="submit"],
.elementor-wpcf7-button-primary button:hover[type="submit"],
.mailchimp-button-primary button:hover,
.wc-proceed-to-checkout a.checkout-button:hover,
.wishlist_table .product-add-to-cart .add_to_cart:hover,
.widget_shopping_cart .buttons .button:hover:nth-child(odd),
.button-primary:active,
input:active[type="reset"],
input:active[type="button"],
input:active[type="submit"],
button:active[type="submit"],
.secondary-button .search-submit:active,
.elementor-wpcf7-button-primary input:active[type="submit"],
.elementor-wpcf7-button-primary button:active[type="submit"],
.mailchimp-button-primary button:active,
.wc-proceed-to-checkout a.checkout-button:active,
.wishlist_table .product-add-to-cart .add_to_cart:active,
.widget_shopping_cart .buttons .button:active:nth-child(odd),
.button-primary.active,
input.active[type="reset"],
input.active[type="button"],
input.active[type="submit"],
button.active[type="submit"],
.secondary-button .active.search-submit,
.elementor-wpcf7-button-primary input.active[type="submit"],
.elementor-wpcf7-button-primary button.active[type="submit"],
.mailchimp-button-primary button.active,
.wc-proceed-to-checkout a.active.checkout-button,
.wishlist_table .product-add-to-cart .active.add_to_cart,
.widget_shopping_cart .buttons .active.button:nth-child(odd),
.show > .button-primary.dropdown-toggle,
.show > input.dropdown-toggle[type="reset"],
.show > input.dropdown-toggle[type="button"],
.show > input.dropdown-toggle[type="submit"],
.show > button.dropdown-toggle[type="submit"],
.secondary-button .show > .dropdown-toggle.search-submit,
.elementor-wpcf7-button-primary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-primary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-primary .show > button.dropdown-toggle,
.mailchimp-button-primary .show > input.dropdown-toggle[type="submit"],
.wc-proceed-to-checkout .show > a.dropdown-toggle.checkout-button,
.wishlist_table .product-add-to-cart .show > .dropdown-toggle.add_to_cart,
.widget_shopping_cart .buttons .show > .dropdown-toggle.button:nth-child(odd),
.elementor-element .elementor-button-primary .elementor-button:hover,
.elementor-element .elementor-button-primary .elementor-button:active,
.elementor-element .elementor-button-primary .elementor-button:focus,
.single-product div.type-product .entry-summary .yith-wcwl-add-to-wishlist > div > a:hover,
.single-product div.type-product .entry-summary .compare:hover,
.woo-variation-swatches .variable-items-wrapper .variable-item.selected:not(.radio-variable-item),
.woo-variation-swatches .variable-items-wrapper .variable-item.selected:not(.radio-variable-item):hover {
  border-color: {$color_primary_hover->toCss()}; }



.vertical-navigation ul.menu > li > a:hover,
.vertical-navigation ul.menu > li > a:hover i,
.button-outline-secondary,
.elementor-wpcf7-button-outline_secondary input[type="button"][type="submit"],
.elementor-wpcf7-button-outline_secondary input[type="submit"],
.elementor-wpcf7-button-outline_secondary button[type="submit"],
.mailchimp-button-outline_secondary button,
.mailchimp-button-outline_secondary button[type="submit"],
.mailchimp-button-outline_secondary input[type="submit"],
.elementor-element .elementor-button-outline_secondary .elementor-button,
.c-secondary,
.author-wrapper .author-name h6,
.contactform-content button.mfp-close,
.site-header-cart .widget_shopping_cart .product_list_widget li .quantity .amount,
.site-header-cart .shopping_cart_nav .product_list_widget li .quantity .amount,
ul.products li .product-price ins,
ul.products li .price ins,
ul.products li.product .product-price ins,
ul.products li.product .price ins,
.single-product div.type-product .summary .price {
  color: {$color_secondary->toCss()}; }


.f-secondary {
  fill: {$color_secondary->toCss()}; }



.button-secondary,
.elementor-wpcf7-button-secondary input[type="button"][type="submit"],
.elementor-wpcf7-button-secondary input[type="submit"],
.elementor-wpcf7-button-secondary button[type="submit"],
.mailchimp-button-secondary button,
.mailchimp-button-secondary button[type="submit"],
.mailchimp-button-secondary input[type="submit"],
.woocommerce-cart .return-to-shop a,
.checkout_coupon .form-row-last button,
#payment .place-order .button,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button,
.widget_shopping_cart .buttons .button,
.elementor-button-secondary button[type="submit"],
.elementor-button-secondary input[type="button"],
.elementor-button-secondary input[type="submit"],
.elementor-element .elementor-button-secondary .elementor-button,
.button-outline-secondary:hover,
.elementor-wpcf7-button-outline_secondary input:hover[type="submit"],
.elementor-wpcf7-button-outline_secondary button:hover[type="submit"],
.mailchimp-button-outline_secondary button:hover,
.mailchimp-button-outline_secondary input:hover[type="submit"],
.button-outline-secondary:active,
.elementor-wpcf7-button-outline_secondary input:active[type="submit"],
.elementor-wpcf7-button-outline_secondary button:active[type="submit"],
.mailchimp-button-outline_secondary button:active,
.mailchimp-button-outline_secondary input:active[type="submit"],
.button-outline-secondary.active,
.elementor-wpcf7-button-outline_secondary input.active[type="submit"],
.elementor-wpcf7-button-outline_secondary button.active[type="submit"],
.mailchimp-button-outline_secondary button.active,
.mailchimp-button-outline_secondary input.active[type="submit"],
.show > .button-outline-secondary.dropdown-toggle,
.elementor-wpcf7-button-outline_secondary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-outline_secondary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-outline_secondary .show > button.dropdown-toggle,
.mailchimp-button-outline_secondary .show > input.dropdown-toggle[type="submit"],
.elementor-element .elementor-button-outline_secondary .elementor-button:hover,
.elementor-element .elementor-button-outline_secondary .elementor-button:active,
.elementor-element .elementor-button-outline_secondary .elementor-button:focus,
.bg-secondary,
#secondary .elementor-widget-wp-widget-categories a:before,
.title-bg-polygon,
.elementor-flip-box__back,
.elementor-text-underline-yes .elementor-icon-list-item:not(:hover) .elementor-icon-list-text:before,
.elementor-teams-wrapper .team-icon-socials a:hover,
.header-button .count {
  background-color: {$color_secondary->toCss()}; }


.form-control:focus,
.button-secondary,
.elementor-wpcf7-button-secondary input[type="button"][type="submit"],
.elementor-wpcf7-button-secondary input[type="submit"],
.elementor-wpcf7-button-secondary button[type="submit"],
.mailchimp-button-secondary button,
.mailchimp-button-secondary button[type="submit"],
.mailchimp-button-secondary input[type="submit"],
.woocommerce-cart .return-to-shop a,
.checkout_coupon .form-row-last button,
#payment .place-order .button,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button,
.widget_shopping_cart .buttons .button,
.elementor-button-secondary button[type="submit"],
.elementor-button-secondary input[type="button"],
.elementor-button-secondary input[type="submit"],
.elementor-element .elementor-button-secondary .elementor-button,
.button-outline-secondary,
.elementor-wpcf7-button-outline_secondary input[type="button"][type="submit"],
.elementor-wpcf7-button-outline_secondary input[type="submit"],
.elementor-wpcf7-button-outline_secondary button[type="submit"],
.mailchimp-button-outline_secondary button,
.mailchimp-button-outline_secondary button[type="submit"],
.mailchimp-button-outline_secondary input[type="submit"],
.elementor-element .elementor-button-outline_secondary .elementor-button,
.button-outline-secondary:hover,
.elementor-wpcf7-button-outline_secondary input:hover[type="submit"],
.elementor-wpcf7-button-outline_secondary button:hover[type="submit"],
.button-outline-secondary:active,
.elementor-wpcf7-button-outline_secondary input:active[type="submit"],
.elementor-wpcf7-button-outline_secondary button:active[type="submit"],
.button-outline-secondary.active,
.elementor-wpcf7-button-outline_secondary input.active[type="submit"],
.elementor-wpcf7-button-outline_secondary button.active[type="submit"],
.show > .button-outline-secondary.dropdown-toggle,
.elementor-wpcf7-button-outline_secondary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-outline_secondary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-outline_secondary .show > button.dropdown-toggle,
.mailchimp-button-outline_secondary .show > input.dropdown-toggle[type="submit"],
.elementor-element .elementor-button-outline_secondary .elementor-button:hover,
.elementor-element .elementor-button-outline_secondary .elementor-button:active,
.elementor-element .elementor-button-outline_secondary .elementor-button:focus,
.b-secondary {
  border-color: {$color_secondary->toCss()}; }




.button-secondary:hover,
.elementor-wpcf7-button-secondary input:hover[type="submit"],
.elementor-wpcf7-button-secondary button:hover[type="submit"],
.mailchimp-button-secondary button:hover,
.mailchimp-button-secondary input:hover[type="submit"],
.woocommerce-cart .return-to-shop a:hover,
.checkout_coupon .form-row-last button:hover,
#payment .place-order .button:hover,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button:hover,
.widget_shopping_cart .buttons .button:hover,
.button-secondary:active,
.elementor-wpcf7-button-secondary input:active[type="submit"],
.elementor-wpcf7-button-secondary button:active[type="submit"],
.mailchimp-button-secondary button:active,
.mailchimp-button-secondary input:active[type="submit"],
.woocommerce-cart .return-to-shop a:active,
.checkout_coupon .form-row-last button:active,
#payment .place-order .button:active,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button:active,
.widget_shopping_cart .buttons .button:active,
.button-secondary.active,
.elementor-wpcf7-button-secondary input.active[type="submit"],
.elementor-wpcf7-button-secondary button.active[type="submit"],
.mailchimp-button-secondary button.active,
.mailchimp-button-secondary input.active[type="submit"],
.woocommerce-cart .return-to-shop a.active,
.checkout_coupon .form-row-last button.active,
#payment .place-order .active.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .active.woocommerce-button,
.widget_shopping_cart .buttons .active.button,
.show > .button-secondary.dropdown-toggle,
.elementor-wpcf7-button-secondary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-secondary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-secondary .show > button.dropdown-toggle,
.mailchimp-button-secondary .show > input.dropdown-toggle[type="submit"],
.woocommerce-cart .return-to-shop .show > a.dropdown-toggle,
.checkout_coupon .form-row-last .show > button.dropdown-toggle,
#payment .place-order .show > .dropdown-toggle.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .show > .dropdown-toggle.woocommerce-button,
.widget_shopping_cart .buttons .show > .dropdown-toggle.button,
.elementor-button-secondary button[type="submit"]:hover,
.elementor-button-secondary button[type="submit"]:active,
.elementor-button-secondary button[type="submit"]:focus,
.elementor-button-secondary input[type="button"]:hover,
.elementor-button-secondary input[type="button"]:active,
.elementor-button-secondary input[type="button"]:focus,
.elementor-button-secondary input[type="submit"]:hover,
.elementor-button-secondary input[type="submit"]:active,
.elementor-button-secondary input[type="submit"]:focus,
.elementor-element .elementor-button-secondary .elementor-button:hover,
.elementor-element .elementor-button-secondary .elementor-button:active,
.elementor-element .elementor-button-secondary .elementor-button:focus {
  background-color: {$color_secondary_hover->toCss()}; }


.button-secondary:hover,
.elementor-wpcf7-button-secondary input:hover[type="submit"],
.elementor-wpcf7-button-secondary button:hover[type="submit"],
.mailchimp-button-secondary button:hover,
.mailchimp-button-secondary input:hover[type="submit"],
.woocommerce-cart .return-to-shop a:hover,
.checkout_coupon .form-row-last button:hover,
#payment .place-order .button:hover,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button:hover,
.widget_shopping_cart .buttons .button:hover,
.button-secondary:active,
.elementor-wpcf7-button-secondary input:active[type="submit"],
.elementor-wpcf7-button-secondary button:active[type="submit"],
.mailchimp-button-secondary button:active,
.mailchimp-button-secondary input:active[type="submit"],
.woocommerce-cart .return-to-shop a:active,
.checkout_coupon .form-row-last button:active,
#payment .place-order .button:active,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button:active,
.widget_shopping_cart .buttons .button:active,
.button-secondary.active,
.elementor-wpcf7-button-secondary input.active[type="submit"],
.elementor-wpcf7-button-secondary button.active[type="submit"],
.mailchimp-button-secondary button.active,
.mailchimp-button-secondary input.active[type="submit"],
.woocommerce-cart .return-to-shop a.active,
.checkout_coupon .form-row-last button.active,
#payment .place-order .active.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .active.woocommerce-button,
.widget_shopping_cart .buttons .active.button,
.show > .button-secondary.dropdown-toggle,
.elementor-wpcf7-button-secondary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-secondary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-secondary .show > button.dropdown-toggle,
.mailchimp-button-secondary .show > input.dropdown-toggle[type="submit"],
.woocommerce-cart .return-to-shop .show > a.dropdown-toggle,
.checkout_coupon .form-row-last .show > button.dropdown-toggle,
#payment .place-order .show > .dropdown-toggle.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .show > .dropdown-toggle.woocommerce-button,
.widget_shopping_cart .buttons .show > .dropdown-toggle.button,
.elementor-button-secondary button[type="submit"]:hover,
.elementor-button-secondary button[type="submit"]:active,
.elementor-button-secondary button[type="submit"]:focus,
.elementor-button-secondary input[type="button"]:hover,
.elementor-button-secondary input[type="button"]:active,
.elementor-button-secondary input[type="button"]:focus,
.elementor-button-secondary input[type="submit"]:hover,
.elementor-button-secondary input[type="submit"]:active,
.elementor-button-secondary input[type="submit"]:focus,
.elementor-element .elementor-button-secondary .elementor-button:hover,
.elementor-element .elementor-button-secondary .elementor-button:active,
.elementor-element .elementor-button-secondary .elementor-button:focus {
  border-color: {$color_secondary_hover->toCss()}; }


CSS;
    return $cssCode;
}
add_filter('osf_customize_grid', 'osf_typography_grid_bootstrap', 10 , 2);
function osf_typography_grid_bootstrap($cssCode, $gridGutter){
    $cssCode .= <<<CSS

.row,
body.opal-content-layout-2cl #content .wrap,
body.opal-content-layout-2cr #content .wrap,
[data-opal-columns],
.site-footer .widget-area,
.comment-form,
.widget .gallery,
.elementor-element .gallery,
.entry-gallery .gallery,
.single .gallery,
[data-elementor-columns],
.single-portfolio-summary .single-portfolio-summary-inner,
.woocommerce-cart .entry-content > .woocommerce,
.woocommerce-billing-fields .woocommerce-billing-fields__field-wrapper,
.woocommerce-MyAccount-content form[class^="woocommerce-"],
.woocommerce-columns--addresses,
form.track_order,
.woocommerce-account .woocommerce,
.woocommerce-account .woocommerce .u-columns.woocommerce-Addresses,
.woocommerce-Addresses,
.woocommerce-address-fields__field-wrapper,
[class*="columns-"] ul.products,
.single-product div.type-product .product-inner {
    margin-right: -{$gridGutter}px;
    margin-left: -{$gridGutter}px;
}



.col-1,
.col-2,
[data-elementor-columns-mobile="6"] .column-item,
.woocommerce.columns-mobile-6 ul.products > li,
.col-3,
[data-elementor-columns-mobile="4"] .column-item,
.woocommerce.columns-mobile-4 ul.products > li,
.col-4,
[data-elementor-columns-mobile="3"] .column-item,
.woocommerce.columns-mobile-3 ul.products > li,
.col-5,
.col-6,
[data-elementor-columns-mobile="2"] .column-item,
.woocommerce.columns-mobile-2 ul.products > li,
.single-product.opal-comment-form-2 .comment-form-author,
.single-product.opal-comment-form-2 .comment-form-email,
.col-7,
.col-8,
.col-9,
.col-10,
.col-11,
.col-12,
.related-posts .column-item,
.opal-content-layout-2cr .related-posts .column-item,
.opal-content-layout-2cl .related-posts .column-item,
.site-footer .widget-area .widget-column,
.comment-form > *,
.comment-form > .comment-form-rating,
.widget .gallery-columns-1 .gallery-item,
.elementor-element .gallery-columns-1 .gallery-item,
.entry-gallery .gallery-columns-1 .gallery-item,
.single .gallery-columns-1 .gallery-item,
[data-elementor-columns-mobile="1"] .column-item,
.single-portfolio-summary .single-portfolio-summary-inner .single-portfolio-summary-meta-title,
.single-portfolio-summary .single-portfolio-summary-meta,
.single-portfolio-summary .single-portfolio-summary-content,
.single-portfolio-summary.col-lg-5 .single-portfolio-summary-meta,
.single-portfolio-summary.col-lg-5 .single-portfolio-summary-content,
.woocommerce-cart .cart-empty,
.woocommerce-cart .return-to-shop,
.woocommerce-billing-fields .form-row-wide,
.woocommerce-MyAccount-content form[class^="woocommerce-"] > *:not(fieldset),
.woocommerce-MyAccount-content form[class^="woocommerce-"] .form-row-wide,
#customer_details [class*='col'],
.woocommerce-Addresses .woocommerce-Address,
.columns-1 ul.products > li,
.woocommerce.columns-mobile-1 ul.products > li,
.col,
body #secondary,
body.opal-content-layout-2cl #primary,
body.opal-content-layout-2cr #primary,
form.track_order p.form-row-first,
form.track_order p.form-row-last,
.columns-5 ul.products > li,
.col-auto,
.col-sm-1,
[data-opal-columns="12"] .column-item,
.col-sm-2,
[data-opal-columns="6"] .column-item,
.columns-6 ul.products > li,
.col-sm-3,
[data-opal-columns="4"] .column-item,
.col-sm-4,
[data-opal-columns="3"] .column-item,
.comment-form .comment-form-url,
.comment-form .comment-form-email,
.comment-form .comment-form-author,
.widget .gallery-columns-6 .gallery-item,
.elementor-element .gallery-columns-6 .gallery-item,
.entry-gallery .gallery-columns-6 .gallery-item,
.single .gallery-columns-6 .gallery-item,
.col-sm-5,
.col-sm-6,
[data-opal-columns="2"] .column-item,
.opal-archive-style-2 .column-item,
.opal-archive-style-5 .column-item,
.opal-archive-style-4 .column-item,
.opal-archive-style-3 .column-item,
.widget .gallery-columns-2 .gallery-item,
.elementor-element .gallery-columns-2 .gallery-item,
.entry-gallery .gallery-columns-2 .gallery-item,
.single .gallery-columns-2 .gallery-item,
.widget .gallery-columns-3 .gallery-item,
.elementor-element .gallery-columns-3 .gallery-item,
.entry-gallery .gallery-columns-3 .gallery-item,
.single .gallery-columns-3 .gallery-item,
.widget .gallery-columns-4 .gallery-item,
.elementor-element .gallery-columns-4 .gallery-item,
.entry-gallery .gallery-columns-4 .gallery-item,
.single .gallery-columns-4 .gallery-item,
.elementor-timeline-view-vertical .timeline-thumbnail,
.elementor-timeline-view-vertical .timeline-content,
.woocommerce-billing-fields .form-row-first,
.woocommerce-billing-fields .form-row-last,
.woocommerce-MyAccount-content form[class^="woocommerce-"] .form-row-first,
.woocommerce-MyAccount-content form[class^="woocommerce-"] .form-row-last,
.columns-2 ul.products > li,
.columns-3 ul.products > li,
.columns-4 ul.products > li,
.opal-content-layout-2cl .columns-3 ul.products li.product,
.opal-content-layout-2cl .columns-3 ul.products > li,
.opal-content-layout-2cr .columns-3 ul.products li.product,
.opal-content-layout-2cr .columns-3 ul.products > li,
.col-sm-7,
.col-sm-8,
.col-sm-9,
.col-sm-10,
.col-sm-11,
.col-sm-12,
[data-opal-columns="1"] .column-item,
.opal-archive-style-2.opal-content-layout-2cr .column-item,
.opal-archive-style-5.opal-content-layout-2cr .column-item,
.opal-archive-style-4.opal-content-layout-2cr .column-item,
.opal-archive-style-3.opal-content-layout-2cr .column-item,
.entry-summary .comment-form .comment-form-url,
.entry-summary .comment-form .comment-form-email,
.entry-summary .comment-form .comment-form-author,
.elementor-widget-opal-image-hotspots .opal-image-hotspots-accordion,
.elementor-widget-opal-image-hotspots .opal-image-hotspots-accordion + .opal-image-hotspots-container,
.cart-collaterals .cross-sells,
.woocommerce-columns--addresses .woocommerce-column,
.woocommerce-account .woocommerce .u-columns [class^="u-column"],
.woocommerce-account .woocommerce-ResetPassword,
.woocommerce-address-fields__field-wrapper .form-row,
.osf-sorting .woocommerce-message,
.osf-sorting .woocommerce-notice,
.col-sm,
.col-sm-auto,
.col-md-1,
.col-md-2,
[data-elementor-columns-tablet="6"] .column-item,
.woocommerce.columns-tablet-6 ul.products > li,
.col-md-3,
[data-elementor-columns-tablet="4"] .column-item,
.woocommerce.columns-tablet-4 ul.products > li,
.col-md-4,
[data-elementor-columns-tablet="3"] .column-item,
.woocommerce.columns-tablet-3 ul.products > li,
.col-md-5,
.col-md-6,
[data-elementor-columns-tablet="2"] .column-item,
.woocommerce.columns-tablet-2 ul.products > li,
.woocommerce-single-style-3.single-product div.product .entry-summary,
.woocommerce-single-style-3.single-product div.product .images,
.woocommerce-single-style-4.single-product div.product .images,
.woocommerce-single-style-4.single-product div.product .entry-summary,
.col-md-7,
.col-md-8,
.col-md-9,
.col-md-10,
.col-md-11,
.col-md-12,
[data-elementor-columns-tablet="1"] .column-item,
.woocommerce-cart .woocommerce-cart-form,
.woocommerce-ResetPassword.lost_reset_password,
.woocommerce-account .woocommerce-MyAccount-navigation,
.woocommerce-account .woocommerce-MyAccount-content,
.woocommerce.columns-tablet-1 ul.products > li,
.single-product div.type-product .entry-summary,
.single-product div.type-product .images,
.col-md,
.col-md-auto,
.col-lg-1,
.col-lg-2,
.col-lg-3,
.col-lg-4,
.col-lg-5,
.col-lg-6,
.woocommerce-single-style-2.single-product div.product .entry-summary,
.woocommerce-single-style-2.single-product div.product .images,
.col-lg-7,
.col-lg-8,
.col-lg-9,
.col-lg-10,
.col-lg-11,
.col-lg-12,
.cart-collaterals,
.col-lg,
.col-lg-auto,
.col-xl-1,
.col-xl-2,
[data-elementor-columns="6"] .column-item,
.woocommerce.columns-6 ul.products > li,
.col-xl-3,
[data-elementor-columns="4"] .column-item,
.woocommerce.columns-4 ul.products > li,
.col-xl-4,
[data-elementor-columns="3"] .column-item,
.woocommerce.columns-3 ul.products > li,
.col-xl-5,
.col-xl-6,
[data-elementor-columns="2"] .column-item,
.woocommerce.columns-2 ul.products > li,
.col-xl-7,
.col-xl-8,
.col-xl-9,
.col-xl-10,
.col-xl-11,
.col-xl-12,
[data-elementor-columns="1"] .column-item,
.woocommerce.columns-1 ul.products > li,
.col-xl,
.col-xl-auto {
    padding-right: {$gridGutter}px;
    padding-left: {$gridGutter}px;
}



.container,
#content,
ul.elementor-nav-menu--dropdown.mega-containerwidth > li.mega-menu-item > .elementor,
.otf-product-recently-content .widget_recently_viewed_products {
    padding-right: {$gridGutter}px;
    padding-left: {$gridGutter}px;
}
  @media (min-width: 576px) {
    .container, #content, ul.elementor-nav-menu--dropdown.mega-containerwidth > li.mega-menu-item > .elementor, .otf-product-recently-content .widget_recently_viewed_products {
      max-width: 540px; } }
  @media (min-width: 768px) {
    .container, #content, ul.elementor-nav-menu--dropdown.mega-containerwidth > li.mega-menu-item > .elementor, .otf-product-recently-content .widget_recently_viewed_products {
      max-width: 720px; } }
  @media (min-width: 992px) {
    .container, #content, ul.elementor-nav-menu--dropdown.mega-containerwidth > li.mega-menu-item > .elementor, .otf-product-recently-content .widget_recently_viewed_products {
      max-width: 960px; } }
  @media (min-width: 1200px) {
    .container, #content, ul.elementor-nav-menu--dropdown.mega-containerwidth > li.mega-menu-item > .elementor, .otf-product-recently-content .widget_recently_viewed_products {
      max-width: 1170px; } }


CSS;
    return $cssCode;
}
add_filter('osf_customize_button_primary_color', 'osf_typography_button_primary_color', 10 , 11);
function osf_typography_button_primary_color($cssCode, $primary, $primary_hover, $primary_border, $primary_border_hover, $primary_color, $primary_color_hover, $primary_color_outline, $button_css, $font_style_code){
    $cssCode .= <<<CSS


.button-primary,
input[type="reset"],
input.secondary[type="button"],
input.secondary[type="reset"],
input.secondary[type="submit"],
input[type="button"],
input[type="submit"],
button[type="submit"],
.secondary-button .search-submit,
.elementor-wpcf7-button-primary input[type="button"][type="submit"],
.elementor-wpcf7-button-primary input[type="submit"],
.elementor-wpcf7-button-primary button[type="submit"],
.mailchimp-button-primary button,
.mailchimp-button-primary button[type="submit"],
.mailchimp-button-primary input[type="submit"],
.wc-proceed-to-checkout a.checkout-button,
.wishlist_table .product-add-to-cart .add_to_cart,
.widget_shopping_cart .buttons .button:nth-child(odd),
.button-default:hover,
.button-dark:hover,
.elementor-element .elementor-button-dark .elementor-button:hover,
.elementor-wpcf7-button-dark input:hover[type="submit"],
.elementor-wpcf7-button-dark button:hover[type="submit"],
.mailchimp-button-dark button:hover,
.mailchimp-button-dark input:hover[type="submit"],
form.woocommerce-form-login .button:hover[type="submit"],
form.register .button:hover[type="submit"],
.button-dark:active,
.elementor-element .elementor-button-dark .elementor-button:active,
.elementor-wpcf7-button-dark input:active[type="submit"],
.elementor-wpcf7-button-dark button:active[type="submit"],
.mailchimp-button-dark button:active,
.mailchimp-button-dark input:active[type="submit"],
form.woocommerce-form-login .button:active[type="submit"],
form.register .button:active[type="submit"],
.button-dark:focus,
.elementor-element .elementor-button-dark .elementor-button:focus,
.elementor-wpcf7-button-dark input:focus[type="submit"],
.elementor-wpcf7-button-dark button:focus[type="submit"],
.mailchimp-button-dark button:focus,
.mailchimp-button-dark input:focus[type="submit"],
form.woocommerce-form-login .button:focus[type="submit"],
form.register .button:focus[type="submit"],
.button-outline-dark:hover,
.elementor-element .elementor-button-outline_dark .elementor-button:hover,
.button-outline-dark:active,
.elementor-element .elementor-button-outline_dark .elementor-button:active,
.button-outline-dark:focus,
.elementor-element .elementor-button-outline_dark .elementor-button:focus,
.button-light:hover,
.elementor-element .elementor-button-light .elementor-button:hover,
.elementor-wpcf7-button-light input:hover[type="submit"],
.elementor-wpcf7-button-light button:hover[type="submit"],
.mailchimp-button-light button:hover,
.mailchimp-button-light input:hover[type="submit"],
.wishlist_table .product-add-to-cart .remove_from_wishlist:hover,
.wishlist_table.mobile li .additional-info-wrapper a.remove_from_wishlist:hover,
.button-light:active,
.elementor-element .elementor-button-light .elementor-button:active,
.elementor-wpcf7-button-light input:active[type="submit"],
.elementor-wpcf7-button-light button:active[type="submit"],
.mailchimp-button-light button:active,
.mailchimp-button-light input:active[type="submit"],
.wishlist_table .product-add-to-cart .remove_from_wishlist:active,
.wishlist_table.mobile li .additional-info-wrapper a.remove_from_wishlist:active,
.button-light:focus,
.elementor-element .elementor-button-light .elementor-button:focus,
.elementor-wpcf7-button-light input:focus[type="submit"],
.elementor-wpcf7-button-light button:focus[type="submit"],
.mailchimp-button-light button:focus,
.mailchimp-button-light input:focus[type="submit"],
.wishlist_table .product-add-to-cart .remove_from_wishlist:focus,
.wishlist_table.mobile li .additional-info-wrapper a.remove_from_wishlist:focus,
.elementor-element .elementor-button-primary .elementor-button {
    background-color: {$primary};
    border-color: {$primary};
    color: {$primary_color};
    {$button_css}
    {$font_style_code}
}



.button-primary:hover,
input:hover[type="reset"],
input:hover[type="button"],
input:hover[type="submit"],
button:hover[type="submit"],
.secondary-button .search-submit:hover,
.elementor-wpcf7-button-primary input:hover[type="submit"],
.elementor-wpcf7-button-primary button:hover[type="submit"],
.mailchimp-button-primary button:hover,
.wc-proceed-to-checkout a.checkout-button:hover,
.wishlist_table .product-add-to-cart .add_to_cart:hover,
.widget_shopping_cart .buttons .button:hover:nth-child(odd),
.button-primary:active,
input:active[type="reset"],
input:active[type="button"],
input:active[type="submit"],
button:active[type="submit"],
.secondary-button .search-submit:active,
.elementor-wpcf7-button-primary input:active[type="submit"],
.elementor-wpcf7-button-primary button:active[type="submit"],
.mailchimp-button-primary button:active,
.wc-proceed-to-checkout a.checkout-button:active,
.wishlist_table .product-add-to-cart .add_to_cart:active,
.widget_shopping_cart .buttons .button:active:nth-child(odd),
.button-primary.active,
input.active[type="reset"],
input.active[type="button"],
input.active[type="submit"],
button.active[type="submit"],
.secondary-button .active.search-submit,
.elementor-wpcf7-button-primary input.active[type="submit"],
.elementor-wpcf7-button-primary button.active[type="submit"],
.mailchimp-button-primary button.active,
.wc-proceed-to-checkout a.active.checkout-button,
.wishlist_table .product-add-to-cart .active.add_to_cart,
.widget_shopping_cart .buttons .active.button:nth-child(odd),
.show > .button-primary.dropdown-toggle,
.show > input.dropdown-toggle[type="reset"],
.show > input.dropdown-toggle[type="button"],
.show > input.dropdown-toggle[type="submit"],
.show > button.dropdown-toggle[type="submit"],
.secondary-button .show > .dropdown-toggle.search-submit,
.elementor-wpcf7-button-primary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-primary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-primary .show > button.dropdown-toggle,
.mailchimp-button-primary .show > input.dropdown-toggle[type="submit"],
.wc-proceed-to-checkout .show > a.dropdown-toggle.checkout-button,
.wishlist_table .product-add-to-cart .show > .dropdown-toggle.add_to_cart,
.widget_shopping_cart .buttons .show > .dropdown-toggle.button:nth-child(odd),
.elementor-element .elementor-button-primary .elementor-button:hover,
.elementor-element .elementor-button-primary .elementor-button:active,
.elementor-element .elementor-button-primary .elementor-button:focus {
    background-color: {$primary_hover};
    border-color: {$primary_hover};
    color: {$primary_color_hover};
    {$button_css}
}


CSS;
    return $cssCode;
}

add_filter('osf_customize_button_secondary_color', 'osf_typography_button_secondary_color', 10 , 11);
function osf_typography_button_secondary_color($cssCode, $secondary, $secondary_hover, $secondary_border, $secondary_border_hover, $secondary_color, $secondary_color_hover, $secondary_color_outline, $button_css, $font_style_code){
    $cssCode .= <<<CSS


.button-secondary,
.elementor-wpcf7-button-secondary input[type="button"][type="submit"],
.elementor-wpcf7-button-secondary input[type="submit"],
.elementor-wpcf7-button-secondary button[type="submit"],
.mailchimp-button-secondary button,
.mailchimp-button-secondary button[type="submit"],
.mailchimp-button-secondary input[type="submit"],
.woocommerce-cart .return-to-shop a,
.checkout_coupon .form-row-last button,
#payment .place-order .button,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button,
.widget_shopping_cart .buttons .button,
.elementor-button-secondary button[type="submit"],
.elementor-button-secondary input[type="button"],
.elementor-button-secondary input[type="submit"],
.elementor-element .elementor-button-secondary .elementor-button {
    background-color: {$secondary};
    border-color: {$secondary};
    color: {$secondary_color};
    {$button_css}
    {$font_style_code}
}



.button-secondary:hover,
.elementor-wpcf7-button-secondary input:hover[type="submit"],
.elementor-wpcf7-button-secondary button:hover[type="submit"],
.mailchimp-button-secondary button:hover,
.mailchimp-button-secondary input:hover[type="submit"],
.woocommerce-cart .return-to-shop a:hover,
.checkout_coupon .form-row-last button:hover,
#payment .place-order .button:hover,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button:hover,
.widget_shopping_cart .buttons .button:hover,
.button-secondary:active,
.elementor-wpcf7-button-secondary input:active[type="submit"],
.elementor-wpcf7-button-secondary button:active[type="submit"],
.mailchimp-button-secondary button:active,
.mailchimp-button-secondary input:active[type="submit"],
.woocommerce-cart .return-to-shop a:active,
.checkout_coupon .form-row-last button:active,
#payment .place-order .button:active,
.woocommerce-MyAccount-content .woocommerce-Pagination .woocommerce-button:active,
.widget_shopping_cart .buttons .button:active,
.button-secondary.active,
.elementor-wpcf7-button-secondary input.active[type="submit"],
.elementor-wpcf7-button-secondary button.active[type="submit"],
.mailchimp-button-secondary button.active,
.mailchimp-button-secondary input.active[type="submit"],
.woocommerce-cart .return-to-shop a.active,
.checkout_coupon .form-row-last button.active,
#payment .place-order .active.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .active.woocommerce-button,
.widget_shopping_cart .buttons .active.button,
.show > .button-secondary.dropdown-toggle,
.elementor-wpcf7-button-secondary .show > input.dropdown-toggle[type="submit"],
.elementor-wpcf7-button-secondary .show > button.dropdown-toggle[type="submit"],
.mailchimp-button-secondary .show > button.dropdown-toggle,
.mailchimp-button-secondary .show > input.dropdown-toggle[type="submit"],
.woocommerce-cart .return-to-shop .show > a.dropdown-toggle,
.checkout_coupon .form-row-last .show > button.dropdown-toggle,
#payment .place-order .show > .dropdown-toggle.button,
.woocommerce-MyAccount-content .woocommerce-Pagination .show > .dropdown-toggle.woocommerce-button,
.widget_shopping_cart .buttons .show > .dropdown-toggle.button,
.elementor-button-secondary button[type="submit"]:hover,
.elementor-button-secondary button[type="submit"]:active,
.elementor-button-secondary button[type="submit"]:focus,
.elementor-button-secondary input[type="button"]:hover,
.elementor-button-secondary input[type="button"]:active,
.elementor-button-secondary input[type="button"]:focus,
.elementor-button-secondary input[type="submit"]:hover,
.elementor-button-secondary input[type="submit"]:active,
.elementor-button-secondary input[type="submit"]:focus,
.elementor-element .elementor-button-secondary .elementor-button:hover,
.elementor-element .elementor-button-secondary .elementor-button:active,
.elementor-element .elementor-button-secondary .elementor-button:focus {
    background-color: {$secondary_hover};
    border-color: {$secondary_hover};
    color: {$secondary_color};
    {$button_css}
    {$font_style_code}
}


CSS;
    return $cssCode;
}
add_filter('osf_customize_typo_heading', 'osf_typography_custom_typo_heading', 10 , 2);
function osf_typography_custom_typo_heading($cssCode, $heading_css){
    $cssCode .= <<<CSS

.typo-heading,
h1,
.site-title,
h2,
h3,
.page-header .page-title,
h4,
h5,
h6,
.h1,
.h2,
.h3,
.h4,
.h5,
.h6,
.tags-links .tags-title,
.vertical-navigation .vertical-navigation-header,
.author-wrapper .author-name,
#secondary .elementor-widget-container h5:first-of-type,
.contactform-content .form-title,
.elementor-cta__status-text,
.elementor-opal-countdown-wrapper .elementor-countdown-item:not(:first-child) .elementor-countdown-digits:before,
.elementor-featured-box-wrapper .elementor-featured-box-title,
.countdown-times > div:not(:first-child):before,
.countdown-times b,
.elementor-teams-wrapper .elementor-team-name,
form.track_order label,
.stock .label,
.single-product div.type-product form.cart .quantity,
.single-product div.type-product table.variations label,
.woocommerce-tabs#osf-accordion-container [data-accordion] [data-control] {
    {$heading_css}
}


CSS;
    return $cssCode;
}
add_filter('osf_customize_typo_tertiary', 'osf_typography_custom_typo_tertiary', 10 , 2);
function osf_typography_custom_typo_tertiary($cssCode, $tertiary_css){
    $cssCode .= <<<CSS

.typo-tertiary,
.elementor-nav-menu--canvas {
    {$tertiary_css}
}


CSS;
    return $cssCode;
}
 
add_filter('osf_customize_typo_quaternary', 'osf_typography_custom_typo_quaternary', 10 , 2);
function osf_typography_custom_typo_quaternary($cssCode, $quaternary_css){
    $cssCode .= <<<CSS

.typo-quaternary {
    {$quaternary_css}
}


CSS;
    return $cssCode;
}
